packagegroup-petalinux-syscontroller: Update machine override
1. Update machine override to match the vck-sc-zynqmp machine conf file.

2. Fix libgpiod dynamic pkgs errors.
ERROR: packagegroup-petalinux-syscontroller-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (libgpiod to libgpiod2)

3. Disable power-advantage-tool due to python3-ipywidgets dependency.
   Disable python3-chipscopy due to python3-plotly dependency. Once
   meta-jupyter port forward to langdale is complete this needs to be
   enabled.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>